library(shiny)
library(ggplot2)

dataset <- ticcompl

value_names <- names(dataset)
names(value_names) <- col_dict

shinyUI(pageWithSidebar(
  
  headerPanel("Insurance Marketing Demo",
              windowTitle='Insurance Marketing Demo'),
  
  sidebarPanel(
    img(src='https://www.google.com/a/gopivotal.com/images/logo.gif?alpha=1&service=google_white'),
    conditionalPanel(
      condition = "input.panelchoice != 'introduction' && input.panelchoice != 'nextsteps'",
      h4("Select plot parameters:"),
      
      sliderInput('sampleSize', 'Sample Size', min=2500, max=nrow(dataset),
                  value=min(4000, nrow(dataset)), step=500, round=0),
      
      selectInput('x', 'X', value_names, selected=names(value_names)[5]),
      selectInput('y', 'Y', value_names, selected=names(value_names)[4]),
      conditionalPanel(
        condition = "input.panelchoice == 'all'",
        selectInput('color', 'Color', c('None', value_names))
      ),
      
      sliderInput('alphaStrength', 'Opacity', min=0, max=1, value=1, step=0.05, round=F),
      
      sliderInput('jitterStrength', 'Jitter', min=0, max=5, value=2, step=0.1, round=F),
      
      conditionalPanel(
        condition = "input.panelchoice == 'marketing'",
        h4("Select and deselect customers groups:"),
        checkboxInput('showSelectX','Show values of X dimension'),
        conditionalPanel(
          condition = "input.showSelectX",
          uiOutput('selectXcontrols')
        ),
        checkboxInput('showSelectY','Show values of Y dimension'),
        conditionalPanel(
          condition = "input.showSelectY",
          uiOutput('selectYcontrols')
        )
      ),
      conditionalPanel(
        condition = "input.panelchoice == 'datascience'",
        h4("Select predictive algorithm:"),
        selectInput('predictFcnName', 'Choose Predictive Algorithm', c("Random Forest" = "predictRandomForest", 
                                                                       "Logistic Regression" = "logisticRegression")),
        sliderInput('classCutoff', 'Classification Cutoff', min=0, max=0.5, value=0.1, step=0.001, round=F)
      ),
      conditionalPanel(
        condition = "input.panelchoice == 'datascience' || input.panelchoice == 'marketing'",
        h4("Cost and Return Values:"),
        textInput("mktCost","Marketing cost per customer",value="1"),
        textInput("mktReturn","Return on new customer",value="100")
      )
    )
  ),
  
  mainPanel(
    tabsetPanel(
      tabPanel("Introduction", 
               h4("This is an interactive Data Science demo by the Pivotal Data Science team (www.gopivotal.com)."),
               p("Imagine the following scenario: An insurance company creates a new product, which is a mobile home/caravan
                 insurance policy. It already has data on their customers and what types of policies they already own, together with
                 external data that contains demographic information on the customers. They want to determine from this which 
                 customers are likely to buy the new mobile home insurance policy. Therefore, the company sends out offers to a number
                 of customers and collects data on responding customers."),
               p("After this, a team is given the task to determine from the collected data which customers want to buy the new
                 mobile home insurance. They can create hypotheses on this 'by hand' and determine customer groups that are likely
                 to buy insurance simply by looking through the data. Alternatively, they could also go with a data-driven approach
                 and use a predictive model to determine the target group. This demo shows how a data-driven approach to select 
                 customers for marketing has advantages over manual 
                 segmentation of the customer base by hand."),
               p("This demo allows you to go through the manual process first and select the best customers for marketing the new
                 insurance policy 'by hand'. Try
                 to be as good as you can here by looking at the dataset and iteratively refine your hypothesis. You can then assign a
                 cost to your marketing campaign so you can see how effectively this budget is spent."),
               p("After this, compare your manual selection to a selection generated by a predictive model. It will use the same cost you
                 assigned earlier and allows you to compare the difference between both approaches. Hopefully, you will
                 find reduced cost and an increasing return rate on a model based marketing campaign."),
               h5("Instructions:"),
               p("You navigate through this demo by clicking on the individual tabs above this text ('Introduction', 'Data Explorer',
                 'Targeting by Hand' and 'Targeting with model support'). You can always come back to this panel to review the
                 instructions."),
               p("To get a general understanding of the dataset and what it looks like, you can explore the dataset on the 
                 'Data Explorer' Tab."),
               p("Since this demo is intended to provide an interactive comparison, on the 'Targeting by Hand' tab you can try to 
                 specify a target group for marketing insurance by hand."),
               p("In contrast, the 'Targeting with model support' tab will walk you through a process in 
                 which a model is fitted to the dataset that predicts which customers are likely to buy an insurance."),
               value="introduction"
      ), 
      tabPanel("Data Explorer", 
               h5("This tab is for general exploration of the dataset."),
               p("On the left hand side you can see the controls for this plot. The plot will update automatically after you change
                 a setting. The 'Sample Size' slider controls how many points of
                 the original dataset you want to see in the plot. It's a good idea to select a sample of only a few thousand points,
                 otherwise the plot will get overcrowded."),
               p("You can also select both X and Y axes of the plot below on the left. You can display a third variable by changing 
                 the 'Color' option on the left, which will color the points in the plot according to this variable. The 'Opacity' allows
                 you to change the transparency of points, to make overlapping points visible. With 'Jitter' you can introduce some
                 random displacement into the plot, also to avoid overlapping points."),
               p("Take your time and explore the dataset carefully! As a tip: You could already start looking for interesting customer
                 groups which might be interested in a new insurance. Set the 'Color' dropdown list to 'No. of mobile home pol.',
                 and you will see customers that bought mobile home insurance in a different color on the plot."),
               plotOutput("plotall"),
               value="all"
      ), 
      tabPanel("Targeting by hand", 
               h5("This tab allows you to select a group for insurance marketing manually."),
               p("The purpose of this tab is to give you the ability to select a target group for insurance marketing yourself. While doing
                 this, you can continually refine your hypothesis by looking at the dataset again and further select/deselect user groups. 
                 The result of your targeting group is shown graphically in the plot below as well as in the success numbers below the plot."),
               p("On the left hand side you can control the parameters of the plot again. Below the plot parameters, it is possible to select
                 and deselect groups of customers for your target group. You can restrict the target group in two dimensions, which are the 
                 same as the ones which are currently visible on the plot."),
               p("You should try to find relevant dimensions for the plot first, which show a clear separability of buyers and non-buyers of
                 the caravan insurance. After you found two dimensions, you can select the customer groups for marketing. Initially, all 
                 customers are selected, that we will market caravan insurance to everyone. Deselect groups that you think will 
                 not buy caravan insurance."),
               p("To assign a concrete dollar value to your marketing success, you can assign a cost to your marketing campaign as well as a
                 return for every new customer for the new caravan insurance. The results based off these numbers are shown below the plot."),
               plotOutput("plotmarketing"),
               p("These are the financial results of the chosen target group selection based off the cost and return values supplied on the 
                 left."),
               #tableOutput("mktconfusionMatrix"),
               tableOutput("mktCostAnalysis"),
               value="marketing"
      ), 
      tabPanel("Targeting with model support", 
               h4("When you first come on this page, the model will be trained. Please wait a few seconds for this to finish..."),
               p("A predictive model is being trained on this tab, to be able to predict which customers are likely to buy caravan insurance.
                 After the model has finished training, you can see an output of the model decision in the plot below. Keep in mind, that
                 with this approach, you're not only limited to two variables, instead the model looks at all variables simultaneously. Below
                 the plot you have the additional information what the financial performance of the model is with your chosen cost and return
                 values and furthermore, which variables are of high importance to the trained model"),
               p("On the left hand side you can control the parameters of the plot like in previous tabs. Below the plot controls you can
                 select what kind of predictive model you want to train (for now, the only option is the 'Random Forest' algorithm).
                 After the model is trained, you have the possibility to change the 'Classification Cutoff' of the model, to adjust how the
                 selective the trained model is in predicting insurance customers. If you set a low cutoff, you will see more predicted 
                 buyers, with a high cutoff the model will become very selective. Below that you can set the cost and return values for
                 marketing"),
               p("After the model is finished training, you should try to set the cutoff to a value such that the return on marketing is
                 comparable to the return on marketing on the previous tab. This allows you to compare both approaches. You will see that
                 the data-driven approach has a significantly higher ROI. You can also choose to be very selective (set a high cutoff) and 
                 you will see the ROI increase very fast. This could give you information about high-value customers in your customer base."),
               #p("Model output, a probability between 0 and 1 for a customer to buy the caravan insurance."),
               #plotOutput("plotdatascience"),
               p("The below plot shows the classification of the customer base into buyers and non-buyers, based on the trained model and
                 the set classification cutoff on the left."),
               plotOutput("plotdatascienceclassification"),
               p("These are the financial results of the chosen target group selection based off the cost and return values supplied on the 
                 left."),
               #tableOutput("dsconfusionMatrix"),
               tableOutput("dsCostAnalysis"),
               #p("Plot of the F-score for different classifation cutoffs."),
               #plotOutput("plotperfcurve"),
               p("The table below should give you some intuition about what the trained model is doing. It shows how important each of the
                 shown variables is to the final model decision and shows the variables in decreasing order of importance. However, it does
                 not give information about what kind of value should be realized for each variable."),
               tableOutput("randomForestVarImp"),
               value="datascience"
      ),
      tabPanel("Next Steps", 
               p("For further info regarding Data Science, please contact:"),
               p("Michael Natusch (mnatusch@gopivotal.com) - Data Science EMEA"),
               p("Greg Whalen (gwhalen@gopivotal.com) - Data Science APJ"),
               p("Alex Luttschyn (aluttschyn@gopivotal.com) - Data Science Americas"),
               value="nextsteps"
      ),
      id="panelchoice")
  )
  
))