library(shiny)
library(ggplot2)

dataset <- ticcompl

value_names <- names(dataset)
names(value_names) <- col_dict

shinyUI(pageWithSidebar(
  
  headerPanel("Insurance Marketing Demo",
              windowTitle='Insurance Marketing Demo'),
  
  sidebarPanel(
    img(src='https://www.google.com/a/gopivotal.com/images/logo.gif?alpha=1&service=google_white'),
    conditionalPanel(
      condition = "input.panelchoice != 'introduction' && input.panelchoice != 'nextsteps' &&
      input.panelchoice != 'modelexplanation'",
      h4("Select plot parameters:"),
      
      sliderInput('sampleSize', 'Sample Size', min=2500, max=nrow(dataset),
                  value=min(4000, nrow(dataset)), step=500, round=0),
      
      selectInput('x', 'X', value_names, selected=names(value_names)[5]),
      selectInput('y', 'Y', value_names, selected=names(value_names)[4]),
      conditionalPanel(
        condition = "input.panelchoice == 'all'",
        selectInput('color', 'Color', c('None', value_names))
      ),
      
      sliderInput('alphaStrength', 'Opacity', min=0, max=1, value=1, step=0.05, round=F),
      
      sliderInput('jitterStrength', 'Jitter', min=0, max=5, value=2, step=0.1, round=F),
      
      conditionalPanel(
        condition = "input.panelchoice == 'marketing'",
        h4("Select and deselect customers groups:"),
        checkboxInput('showSelectX','Show values of X dimension',value=T),
        conditionalPanel(
          condition = "input.showSelectX",
          uiOutput('selectXcontrols')
        ),
        checkboxInput('showSelectY','Show values of Y dimension',value=T),
        conditionalPanel(
          condition = "input.showSelectY",
          uiOutput('selectYcontrols')
        )
      ),
      conditionalPanel(
        condition = "input.panelchoice == 'datascience'",
        h4("Select predictive algorithm:"),
        selectInput('predictFcnName', 'Choose Predictive Algorithm', c("Random Forest" = "predictRandomForest", 
                                                                       "Logistic Regression" = "logisticRegression")),
        sliderInput('classCutoff', 'Classification Cutoff', min=0, max=0.5, value=0.1, step=0.001, round=F)
      ),
      conditionalPanel(
        condition = "input.panelchoice == 'datascience' || input.panelchoice == 'marketing'",
        h4("Cost and Return Values:"),
        textInput("mktCost","Marketing cost per customer",value="1"),
        textInput("mktReturn","Return on new customer",value="100")
      )
    )
  ),
  
  mainPanel(
    tabsetPanel(
      tabPanel("Introduction", 
               h5("This is an interactive Data Science demo by the Pivotal Data Science team (",a(href="http://www.gopivotal.com",'www.gopivotal.com'),")."),
               h4("Scenario"),
               p("An insurance company creates a new product, which is a mobile home/caravan
                 insurance policy. It already has data on their customers and what types of policies they already own, together with
                 external data that contains demographic information on the customers. They want to determine from this which 
                 customers are likely to buy the new mobile home insurance policy. Therefore, the company sends out offers to a number
                 of customers and collects data on responding customers."),
               p("After this, a team is given the task to determine from the collected data which customers want to buy the new
                 mobile home insurance. They can create hypotheses on this in a traditional way and determine customer groups that are likely
                 to buy insurance simply by looking through the data. Alternatively, they could also go with a data-driven approach
                 and use a predictive model to determine the target group."),
               h4("Concept"),
               p("This demo shows how a data-driven approach to select customers for marketing has advantages over a traditional approach. 
                 It allows you to go through the manual process first and select the best customers to market the new
                 insurance policy to in a traditional way. You can then assign a
                 cost to your marketing campaign so you can see how effectively this budget is spent."),
               p("After this, compare your manual selection to a selection generated by a predictive model based on Machine Learning.
                 It will use the same cost you assigned earlier and allows you to compare the difference between both approaches. 
                 Hopefully, you will find reduced cost and an increasing return rate on a model based marketing campaign."),
               h4("Instructions"),
               p(HTML("
                  <ul>
                    <li>You navigate through this demo by clicking on the individual tabs on the top. You can always come back to this 
                        panel to review the instructions.</li>
                    <li>To get a general understanding of the dataset and what it looks like, you can explore the dataset on the 
                        'Data Explorer' Tab.</li>
                    <li>Since this demo is intended to provide an interactive comparison, on the 'Targeting by Hand' tab you can try to 
                        specify a target group for marketing insurance by hand.</li>
                    <li>In contrast, the 'Targeting with model support' tab will walk you through a process in 
                        which a model is fitted to the dataset that predicts which customers are likely to buy an insurance.</li>
                  </ul>")),
               value="introduction"
      ), 
      tabPanel("Data Explorer", 
               h4("Instructions"),
               h5("This tab is for general exploration of the dataset."),
               p(HTML("
                  On the left hand side you can see the controls for this plot. The plot will update automatically after you change
                  a setting.
                  <ul>
                    <li>The <strong>'Sample Size'</strong> slider controls how many points of
                        the original dataset you want to see in the plot. It's a good idea to select a sample of only a few thousand points,
                        otherwise the plot will get overcrowded.</li>
                    <li>You can also select both <strong>X and Y axes</strong> of the plot below on the left.</li>
                    <li>You can display a third variable by changing the <strong>'Color'</strong> option on the left , which will color the points
                        in the plot according to this variable.</li>
                    <li>The <strong>'Opacity'</strong> allows you to change the transparency of points, to make overlapping points visible.</li>
                    <li>With <strong>'Jitter'</strong> you can introduce some random displacement into the plot, also to avoid overlapping points.</li>
                  </ul>")),
               p(strong("Tip:"),"You could already start looking for interesting customer
                 groups which might be interested in a new insurance. Set the 'Color' dropdown list to 'No. of mobile home pol.',
                 and you will see customers that bought mobile home insurance in a different color on the plot."),
               plotOutput("plotall"),
               value="all"
      ), 
      tabPanel("Traditional Targeting", 
               h4("Background"),
               h5("This tab allows you to select a group for insurance marketing manually."),
               p("The purpose of this tab is to give you the ability to select a target group for insurance marketing yourself. While doing
                 this, you can continually refine your hypothesis by looking at the dataset again and further select/deselect user groups. 
                 The result of your targeting group is shown graphically in the plot below as well as in the success numbers below the plot."),
               h4("Instructions"),
               p(HTML("
                  <ul>
                    <li>On the left hand side you can control the <strong>plot parameters</strong> like in the previous tab.</li>
                    <li>Below the plot parameters, it is possible to <strong>select and deselect customer groups for your marketing target group</strong>.
                        You can restrict the target group in the same dimensions that are currently visible on the plot.</li>
                    <li>To assign a concrete dollar value to your marketing success, you can assign a <strong>cost to your marketing</strong> 
                        campaign as well as a <strong>return for every new customer</strong> for the new caravan insurance. The results based off 
                        these numbers are shown below the plot. This will influence the financial result shown in the table below the plot.</li>
                  </ul>")),
               p(strong("Tip:"),"You should try to find relevant dimensions for the plot first, which show a clear separability of buyers and non-buyers of
                 the caravan insurance. After you found two dimensions, you can select the customer groups for marketing. ",strong("Initially, all 
                 customers are selected,"),"which means we will market caravan insurance to everyone. Deselect groups that you think will 
                 not buy caravan insurance."),
               h4("Results"),
               plotOutput("plotmarketing"),
               p("These are the financial results of the chosen target group selection based off the cost and return values supplied on the 
                 left."),
               #tableOutput("mktconfusionMatrix"),
               tableOutput("mktCostAnalysis"),
               explanationsList,
               value="marketing"
      ), 
      tabPanel("Model Explanations", 
               h4("Model Explanations go here"),
               value="modelexplanation"
      ),
      tabPanel("Targeting with model support", 
               conditionalPanel(condition="$('div#plotdatascienceclassification').contents().length==0 || 
                                           $('div#plotdatascienceclassification').hasClass('recalculating')",
                                h3("Please wait a few seconds for the model to finish training...")),
               h4("Background"),
               p("On this tab, a Machine Learning model is being trained that predicts which customers are likely to buy caravan insurance.
                 After the model has finished training, you can see an output of the model decision in the plot below. Keep in mind, that
                 with this approach, you're not only limited to two variables, instead the model looks at all variables simultaneously. Below
                 the plot you have the additional information what the financial performance of the model is with your chosen cost and return
                 values and furthermore, which variables are of high importance to the trained model"),
               p(strong("Note:"),"Remember that the data we have on the customers does not come from the insurance company only (which is only his 
                 number of certain policies and his contributions to them). On every customer
                 we have ",strong("external data"),", which in this demo is information about the ",strong("demographics in his zip code"),".
                 It could also be
                 data from social networks, for example. This external data is what allows the model to make good predictions, since
                 this data contains a lot more information about the customer than the insurance company's data."),
               h4("Instructions"),
               p(HTML("
                  <ul>
                    <li>On the left hand side you can control the <strong>plot parameters</strong> like in previous tabs.</li>
                    <li>Below this, you can select what kind of <strong>predictive algorithm</strong> you want to train (for now, the only option 
                        is the 'Random Forest' algorithm).</li>
                    <li>After the Machine Learning model is trained, you have the possibility to change the <strong>'Classification Cutoff'</strong> 
                        of the model, to adjust how sensitive the trained model is in predicting insurance customers: If you set a 
                        <strong>low cutoff</strong>, you will see <strong>more predicted buyers</strong>, with a <strong>high cutoff</strong> the 
                        model will predict that <strong>less people are buyers</strong>.</li>
                    <li>Below that you can set the <strong>cost and return</strong> values for marketing. This will influence the financial result 
                        in the table below the plot.</li>
                  </ul>")),
               h4("Results"),
               #p("Model output, a probability between 0 and 1 for a customer to buy the caravan insurance."),
               #plotOutput("plotdatascience"),
               p("The below plot shows the classification of the customer base, based on the trained model and specified classification cutoff:"),
               conditionalPanel(condition="$('div#plotdatascienceclassification').contents().length==0 || 
                                           $('div#plotdatascienceclassification').hasClass('recalculating')",
                                div(align="center",style="height: 400px",img(src="loading.gif"))),
               conditionalPanel(condition="!($('div#plotdatascienceclassification').contents().length==0 || 
                                           $('div#plotdatascienceclassification').hasClass('recalculating'))",
                                plotOutput("plotdatascienceclassification")),
               #conditionalPanel(condition="!($('div#baseline').text()=='' || $('html').hasClass('shiny-busy'))", br()),
               #plotOutput("plotdatascienceclassification"),
               p("In the table below are the financial results of the chosen target group selection based off the cost and return values 
                 supplied on the left. ",br(),strong("Tip:"),"After the model has finished training, you should try to set the cutoff to a 
                 value such that the realized return on Model Targeting and Traditional Targeting is approximately the same. This allows you 
                 to compare both approaches."),
               #tableOutput("dsconfusionMatrix"),
               conditionalPanel(condition="$('div#plotdatascienceclassification').contents().length==0 || 
                                           $('div#plotdatascienceclassification').hasClass('recalculating')",
                                div(align="center",img(src="loading.gif"))),
               conditionalPanel(condition="!($('div#plotdatascienceclassification').contents().length==0 || 
                                           $('div#plotdatascienceclassification').hasClass('recalculating'))",
                                tableOutput("dsCostAnalysis")),
               p(strong("You can see that
                 the data-driven approach has a significantly higher ROI. You can also choose to be very selective (set a high cutoff) and 
                 you will see the ROI increase very fast. This could give you information about high-value customers in your customer base.")),
               explanationsList,
               #p("Plot of the F-score for different classifation cutoffs."),
               #plotOutput("plotperfcurve"),
               h4("Model Details"),
               p("The table below should give you some intuition about what the trained model is doing. It shows how important each of the
                 shown variables is to the final model decision and shows the variables in decreasing order of importance."),
               conditionalPanel(condition="$('div#plotdatascienceclassification').contents().length==0 || 
                                           $('div#plotdatascienceclassification').hasClass('recalculating')",
                                div(align="center",img(src="loading.gif"))),
               conditionalPanel(condition="!($('div#plotdatascienceclassification').contents().length==0 || 
                                           $('div#plotdatascienceclassification').hasClass('recalculating'))",
                                tableOutput("randomForestVarImp")),
               value="datascience"
      ),
      tabPanel("Next Steps", 
               p("For further infor regarding this demo and Data Science, please contact:"),
               p("Alexander Kagoshima - akagoshima@gopivotal.com"),
#                p("For further info regarding this demo aData Science, please contact:"),
#                p("Michael Natusch (mnatusch@gopivotal.com) - Data Science EMEA"),
#                p("Greg Whalen (gwhalen@gopivotal.com) - Data Science APJ"),
#                p("Alex Luttschyn (aluttschyn@gopivotal.com) - Data Science Americas"),
               value="nextsteps"
      ),
      id="panelchoice")
  )
  
))